# This file was generated by GoReleaser. DO NOT EDIT.
cask "clockify-cli" do
  name "clockify-cli"
  desc "Helps to interact with Clockfy's API"
  homepage "https://github.com/lucassabreu/clockify-cli"
  version "0.60.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clockify-cli"

  on_macos do
    on_intel do
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Darwin_x86_64.tar.gz"
      sha256 "a017137d14f44603992699ef771ddf5cd40879b8c99a5159cbf9263e18130364"
    end
    on_arm do
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Darwin_arm64.tar.gz"
      sha256 "17ac6b4f398c2067d71357bfbf5143c994511e08cd93ad589b2565b2bd88aa4d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Linux_x86_64.tar.gz"
      sha256 "6fe4cef86d185fedb7eb7e5a0489c0e29570c28b44c0deb4994c0ba123651264"
    end
    on_arm do
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Linux_arm64.tar.gz"
      sha256 "44037c9b3f8e94617ee91f42a5d56e8d0e5e0f06ee855d87669b0f768df39be9"
    end
  end

  # No zap stanza required
end
