# This file was generated by GoReleaser. DO NOT EDIT.
cask "clockify-cli" do
  version "0.64.2"

  on_macos do
    on_intel do
      sha256 "83ef181af9324068de2a2820f9a4f6833b6d15df1b02d4407e4d5e7c176c6fbf"
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "5237b3f4532a144cdbe02845c4195718c62f0d028303a531cc12ee9a16a08a9e"
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9c4b19a2f8581ba658fd4a68695fe008dbf8fb8a6c0444282ed15cbb06077f3e"
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "d918ac8a29c3b5ea716510617618022bad223bbe4ec88657f07deae2d54d18c8"
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Linux_arm64.tar.gz"
    end
  end

  name "clockify-cli"
  desc "Helps to interact with Clockfy's API"
  homepage "https://github.com/lucassabreu/clockify-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clockify-cli"

  # No zap stanza required

end
