# This file was generated by GoReleaser. DO NOT EDIT.
cask "clockify-cli" do
  version "0.61.2"

  on_macos do
    on_intel do
      sha256 "30ecd28a3e732d2830142b94856fba864049a22b83c64e2479f8eb38014fffec"
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1e1c85501a318fa1d3c6a5029b0317ee8919f459a8d463c43ed96b4e77c4b437"
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e06e3d4edd40ae14f57c32b5845330253e7fe4b5273a722ba02ba5abe86fb45c"
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "180359ab3ea446e2056ea0c48a0fef69e8db4602bc9a1f380edbfacf51079fa1"
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v#{version}/clockify-cli_Linux_arm64.tar.gz"
    end
  end

  name "clockify-cli"
  desc "Helps to interact with Clockfy's API"
  homepage "https://github.com/lucassabreu/clockify-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "clockify-cli"

  # No zap stanza required

end
