# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClockifyCli < Formula
  desc "Helps to interact with Clockfy's API"
  homepage "https://github.com/lucassabreu/clockify-cli"
  version "0.44.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v0.44.2/clockify-cli_0.44.2_Darwin_x86_64.tar.gz"
      sha256 "ff89c48a44eb24b37fb83aadeff9c7dbf7105fdc9f333c0cf8c1b1a0be6d7533"

      def install
        bin.install "clockify-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v0.44.2/clockify-cli_0.44.2_Darwin_arm64.tar.gz"
      sha256 "ea07ae7cfd625974c6ee9dd331ebe9725dfa188be7e1933fbbbf7225235e0942"

      def install
        bin.install "clockify-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v0.44.2/clockify-cli_0.44.2_Linux_x86_64.tar.gz"
      sha256 "04032411541dfac570b2833447c1c5fe9a24fa5c0baeda24032bc5c57c8a0807"

      def install
        bin.install "clockify-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v0.44.2/clockify-cli_0.44.2_Linux_arm64.tar.gz"
      sha256 "f35b06a8d3cccc342dbb8f7c3a03265689faf4172564bdd71fd25b7d0b1cd95f"

      def install
        bin.install "clockify-cli"
      end
    end
  end

  test do
    system "#{bin}/clockify-cli version"
  end
end
