# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClockifyCli < Formula
  desc "Helps to interact with Clockfy's API"
  homepage "https://github.com/lucassabreu/clockify-cli"
  version "0.52.0"

  on_macos do
    on_intel do
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v0.52.0/clockify-cli_Darwin_x86_64.tar.gz"
      sha256 "2711440b128e98ca3b2173681f8c39841b29799114754e6cb8c48515fc65e4cd"

      def install
        bin.install "clockify-cli"
      end
    end
    on_arm do
      url "https://github.com/lucassabreu/clockify-cli/releases/download/v0.52.0/clockify-cli_Darwin_arm64.tar.gz"
      sha256 "675110a04af9923442469c562d008140d98d295027e0256cd6417de47ed612cb"

      def install
        bin.install "clockify-cli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lucassabreu/clockify-cli/releases/download/v0.52.0/clockify-cli_Linux_x86_64.tar.gz"
        sha256 "04ba1f6cc34cc7703166a4e5b0887387f0de462f2bddd1b95cc203997f374433"

        def install
          bin.install "clockify-cli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lucassabreu/clockify-cli/releases/download/v0.52.0/clockify-cli_Linux_arm64.tar.gz"
        sha256 "3b45a119ec66c34a82a0c4af0846d779459b1e5eff0e3ea4dd3c9f0c3968d70d"

        def install
          bin.install "clockify-cli"
        end
      end
    end
  end

  test do
    system "#{bin}/clockify-cli version"
  end
end
